In [8]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
df = pd.DataFrame(scores,
             columns = ["國文","英文","地理","人文","氣候"],
             index=[f"stu{i}" for i in range(1,51)]
)
df['國文']
df['英文']
df[['國文','地理']]
df

       國文  英文   地理  人文   氣候
stu1   54  99   68  77   74
stu2   92  67   94  61   50
stu3   89  82   56  82   66
stu4   62  90   93  77   54
stu5   89  71   94  94   80
stu6   98  61   93  88   72
stu7   98  56   51  85   72
stu8   64  86   95  94   65
stu9   51  94   87  55   95
stu10  72  64  100  66   61
stu11  93  70   74  80   83
stu12  87  88   66  55   51
stu13  70  55   88  78   97
stu14  64  73   68  83   71
stu15  82  74   52  90   56
stu16  60  70   75  90   95
stu17  77  89   63  65   63
stu18  78  97   55  75   85
stu19  85  88   76  58  100
stu20  82  55   88  95   88
stu21  50  93   92  81   93
stu22  73  68   79  51   94
stu23  85  53   71  76   55
stu24  84  76   91  54   72
stu25  99  82  100  60   64
stu26  80  91   67  75   70
stu27  71  57   62  64   93
stu28  84  92   53  81   81
stu29  93  52   88  76   71
stu30  94  53   96  94   95
stu31  92  60   69  54   52
stu32  63  69   57  77   53
stu33  76  61   91  73   69
stu34  80  79  100  72   76
stu35  65  73   64  93   73
stu36  71  94   59  84   56
stu37  63  62   73  55   98
stu38  81  53   66  83   85
stu39  98  73   66  96  100
stu40  60  87   72  76   74
stu41  86  69   95  57   75
stu42  73  58   86  55   84
stu43  82  85   59  90   98
stu44  74  56   50  78   85
stu45  73  75   95  80   90
stu46  99  72   64  86   50
stu47  56  75   95  95   56
stu48  90  83   56  84   74
stu49  77  87   64  81   84
stu50  83  97   69  94   98

In [10]:
df.loc['stu1']
df.loc[['stu1','stu50']]

       國文  英文  地理  人文  氣候
stu1   54  99  68  77  74
stu50  83  97  69  94  98